---
- hosts: KUBE_APISERVER
  become: yes
  gather_facts: false

  roles:
    - role: common
      tags: common
    - role: users
      tags: users
    - role: filebeat
      tags: filebeat
    - role: admin-account
      tags: admin-account
    - role: service-account
      tags: service-account
    - role: kube-apiserver
      tags: kube-apiserver
    - role: cilium
      tags:
        - cilium
        - never
    - role: coredns
      tags:
        - coredns
        - never
    - role: csr
      tags:
        - csr
        - never

